# Generated by Django 5.1.1 on 2024-12-06 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_frequencia_nota_boletim'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='materia',
            name='nome_materia',
            field=models.CharField(choices=[('Matematica', 'Matemática'), ('Portugues', 'Português'), ('Historia', 'História'), ('Geografia', 'Geografia'), ('Ciencias', 'Ciências'), ('Ingles', 'Inglês'), ('Arte', 'Arte'), ('Educacao Fisica', 'Educação Física'), ('Religiao', 'Religião'), ('Filosofia', 'Filosofia')], default='Matematica', max_length=100),
        ),
    ]
