# Generated by Django 5.1.1 on 2024-12-06 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_materia_descricao_alter_materia_nome_materia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='especialidade',
        ),
    ]
