# Generated by Django 5.1.1 on 2024-12-06 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_professor_especialidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atribuicao',
            name='data_fim',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nota',
            name='disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.materia'),
        ),
    ]
