# Generated by Django 5.1.1 on 2024-12-06 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_atribuicao_data_fim_alter_nota_disciplina'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='disciplinas',
            field=models.ManyToManyField(related_name='professores', to='core.materia'),
        ),
    ]
