# Generated by Django 5.1.1 on 2024-12-07 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_professor_disciplinas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atribuicao',
            name='data_fim',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='atribuicao',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atribuicoes', to='core.professor'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='turno',
            field=models.CharField(choices=[('M', 'Manhã'), ('T', 'Tarde'), ('N', 'Noite')], max_length=1),
        ),
    ]
